[Sat Feb 02 13:32:52.490536 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840] [2019-02-02 13:32:52,488] ERROR in app: Exception on /login [POST]
[Sat Feb 02 13:32:52.490575 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840] Traceback (most recent call last):
[Sat Feb 02 13:32:52.490580 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
[Sat Feb 02 13:32:52.490584 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]     response = self.full_dispatch_request()
[Sat Feb 02 13:32:52.490587 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Sat Feb 02 13:32:52.490591 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]     rv = self.handle_user_exception(e)
[Sat Feb 02 13:32:52.490594 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
[Sat Feb 02 13:32:52.490598 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]     reraise(exc_type, exc_value, tb)
[Sat Feb 02 13:32:52.490601 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
[Sat Feb 02 13:32:52.490605 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]     raise value
[Sat Feb 02 13:32:52.490608 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Sat Feb 02 13:32:52.490611 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]     rv = self.dispatch_request()
[Sat Feb 02 13:32:52.490615 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
[Sat Feb 02 13:32:52.490618 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]     return self.view_functions[rule.endpoint](**req.view_args)
[Sat Feb 02 13:32:52.490622 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]   File "/home/bartek/flask/moi/routes.py", line 38, in login
[Sat Feb 02 13:32:52.490626 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840]     salt = user.salt
[Sat Feb 02 13:32:52.490630 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840] AttributeError: 'NoneType' object has no attribute 'salt'
[Sat Feb 02 13:32:52.490655 2019] [wsgi:error] [pid 4344:tid 139842845202176] [remote 127.0.0.1:44840] 
[Sat Feb 02 17:53:19.715779 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378] [2019-02-02 17:53:19,711] ERROR in app: Exception on /logged [GET]
[Sat Feb 02 17:53:19.716006 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378] Traceback (most recent call last):
[Sat Feb 02 17:53:19.716025 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
[Sat Feb 02 17:53:19.716048 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     response = self.full_dispatch_request()
[Sat Feb 02 17:53:19.716053 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Sat Feb 02 17:53:19.716056 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     rv = self.handle_user_exception(e)
[Sat Feb 02 17:53:19.716060 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
[Sat Feb 02 17:53:19.716071 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     reraise(exc_type, exc_value, tb)
[Sat Feb 02 17:53:19.716075 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
[Sat Feb 02 17:53:19.716078 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     raise value
[Sat Feb 02 17:53:19.716081 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Sat Feb 02 17:53:19.716084 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     rv = self.dispatch_request()
[Sat Feb 02 17:53:19.716088 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
[Sat Feb 02 17:53:19.716091 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     return self.view_functions[rule.endpoint](**req.view_args)
[Sat Feb 02 17:53:19.716094 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/flask/moi/routes.py", line 57, in logged
[Sat Feb 02 17:53:19.716097 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     return render_template('logged.html', title = 'Welcome', form=form)
[Sat Feb 02 17:53:19.716101 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
[Sat Feb 02 17:53:19.716104 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
[Sat Feb 02 17:53:19.716107 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
[Sat Feb 02 17:53:19.716111 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     return self.get_template(template_name_or_list, parent, globals)
[Sat Feb 02 17:53:19.716114 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
[Sat Feb 02 17:53:19.716117 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     return self._load_template(name, self.make_globals(globals))
[Sat Feb 02 17:53:19.716120 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
[Sat Feb 02 17:53:19.716124 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     template = self.loader.load(self, name, globals)
[Sat Feb 02 17:53:19.716127 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
[Sat Feb 02 17:53:19.716130 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     source, filename, uptodate = self.get_source(environment, name)
[Sat Feb 02 17:53:19.716133 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
[Sat Feb 02 17:53:19.716136 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     return self._get_source_fast(environment, template)
[Sat Feb 02 17:53:19.716140 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
[Sat Feb 02 17:53:19.716147 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378]     raise TemplateNotFound(template)
[Sat Feb 02 17:53:19.716153 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378] jinja2.exceptions.TemplateNotFound: logged.html
[Sat Feb 02 17:53:19.716184 2019] [wsgi:error] [pid 8380:tid 139842845202176] [remote 127.0.0.1:46378] 
[Sat Feb 02 17:54:12.269565 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382] [2019-02-02 17:54:12,266] ERROR in app: Exception on /logged [GET]
[Sat Feb 02 17:54:12.269594 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382] Traceback (most recent call last):
[Sat Feb 02 17:54:12.269598 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
[Sat Feb 02 17:54:12.269602 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     response = self.full_dispatch_request()
[Sat Feb 02 17:54:12.269606 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Sat Feb 02 17:54:12.269609 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     rv = self.handle_user_exception(e)
[Sat Feb 02 17:54:12.269613 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
[Sat Feb 02 17:54:12.269616 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     reraise(exc_type, exc_value, tb)
[Sat Feb 02 17:54:12.269620 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
[Sat Feb 02 17:54:12.269623 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     raise value
[Sat Feb 02 17:54:12.269626 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Sat Feb 02 17:54:12.269630 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     rv = self.dispatch_request()
[Sat Feb 02 17:54:12.269633 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
[Sat Feb 02 17:54:12.269636 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     return self.view_functions[rule.endpoint](**req.view_args)
[Sat Feb 02 17:54:12.269640 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/flask/moi/routes.py", line 57, in logged
[Sat Feb 02 17:54:12.269643 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     return render_template('logged.html', title = 'Welcome', form=form)
[Sat Feb 02 17:54:12.269647 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
[Sat Feb 02 17:54:12.269650 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
[Sat Feb 02 17:54:12.269654 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
[Sat Feb 02 17:54:12.269657 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     return self.get_template(template_name_or_list, parent, globals)
[Sat Feb 02 17:54:12.269660 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
[Sat Feb 02 17:54:12.269670 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     return self._load_template(name, self.make_globals(globals))
[Sat Feb 02 17:54:12.269673 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
[Sat Feb 02 17:54:12.269677 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     template = self.loader.load(self, name, globals)
[Sat Feb 02 17:54:12.269680 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
[Sat Feb 02 17:54:12.269683 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     code = environment.compile(source, name, filename)
[Sat Feb 02 17:54:12.269686 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
[Sat Feb 02 17:54:12.269689 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     self.handle_exception(exc_info, source_hint=source_hint)
[Sat Feb 02 17:54:12.269692 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
[Sat Feb 02 17:54:12.269695 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     reraise(exc_type, exc_value, tb)
[Sat Feb 02 17:54:12.269698 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
[Sat Feb 02 17:54:12.269701 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     raise value.with_traceback(tb)
[Sat Feb 02 17:54:12.269704 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/flask/moi/templates/logged.html", line 7, in template
[Sat Feb 02 17:54:12.269706 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     <div>
[Sat Feb 02 17:54:12.269709 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
[Sat Feb 02 17:54:12.269712 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     return Parser(self, source, name, encode_filename(filename)).parse()
[Sat Feb 02 17:54:12.269715 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
[Sat Feb 02 17:54:12.269718 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     result = nodes.Template(self.subparse(), lineno=1)
[Sat Feb 02 17:54:12.269721 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
[Sat Feb 02 17:54:12.269724 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     rv = self.parse_statement()
[Sat Feb 02 17:54:12.269727 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
[Sat Feb 02 17:54:12.269730 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     return getattr(self, 'parse_' + self.stream.current.value)()
[Sat Feb 02 17:54:12.269733 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
[Sat Feb 02 17:54:12.269736 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     node.body = self.parse_statements(('name:endblock',), drop_needle=True)
[Sat Feb 02 17:54:12.269742 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
[Sat Feb 02 17:54:12.269745 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     result = self.subparse(end_tokens)
[Sat Feb 02 17:54:12.269749 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 875, in subparse
[Sat Feb 02 17:54:12.269752 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     add_data(self.parse_tuple(with_condexpr=True))
[Sat Feb 02 17:54:12.269755 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 620, in parse_tuple
[Sat Feb 02 17:54:12.269758 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     args.append(parse())
[Sat Feb 02 17:54:12.269761 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 432, in parse_expression
[Sat Feb 02 17:54:12.269764 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     return self.parse_condexpr()
[Sat Feb 02 17:54:12.269767 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 437, in parse_condexpr
[Sat Feb 02 17:54:12.269770 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     expr1 = self.parse_or()
[Sat Feb 02 17:54:12.269772 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 450, in parse_or
[Sat Feb 02 17:54:12.269775 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     left = self.parse_and()
[Sat Feb 02 17:54:12.269778 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 459, in parse_and
[Sat Feb 02 17:54:12.269781 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     left = self.parse_not()
[Sat Feb 02 17:54:12.269784 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 470, in parse_not
[Sat Feb 02 17:54:12.269787 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     return self.parse_compare()
[Sat Feb 02 17:54:12.269790 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 480, in parse_compare
[Sat Feb 02 17:54:12.269793 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     ops.append(nodes.Operand(token_type, self.parse_math1()))
[Sat Feb 02 17:54:12.269796 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 496, in parse_math1
[Sat Feb 02 17:54:12.269799 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     left = self.parse_concat()
[Sat Feb 02 17:54:12.269802 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 507, in parse_concat
[Sat Feb 02 17:54:12.269805 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     args = [self.parse_math2()]
[Sat Feb 02 17:54:12.269808 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 517, in parse_math2
[Sat Feb 02 17:54:12.269814 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     left = self.parse_pow()
[Sat Feb 02 17:54:12.269817 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 528, in parse_pow
[Sat Feb 02 17:54:12.269820 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     left = self.parse_unary()
[Sat Feb 02 17:54:12.269823 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 546, in parse_unary
[Sat Feb 02 17:54:12.269826 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     node = self.parse_primary()
[Sat Feb 02 17:54:12.269829 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 583, in parse_primary
[Sat Feb 02 17:54:12.269832 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     self.fail("unexpected '%s'" % describe_token(token), token.lineno)
[Sat Feb 02 17:54:12.269835 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
[Sat Feb 02 17:54:12.269838 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382]     raise exc(msg, lineno, self.name, self.filename)
[Sat Feb 02 17:54:12.269843 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382] jinja2.exceptions.TemplateSyntaxError: unexpected '<'
[Sat Feb 02 17:54:12.269867 2019] [wsgi:error] [pid 8432:tid 139842836809472] [remote 127.0.0.1:46382] 
[Sat Feb 02 17:56:53.436059 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386] [2019-02-02 17:56:53,434] ERROR in app: Exception on /logged [GET]
[Sat Feb 02 17:56:53.436094 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386] Traceback (most recent call last):
[Sat Feb 02 17:56:53.436098 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
[Sat Feb 02 17:56:53.436102 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     response = self.full_dispatch_request()
[Sat Feb 02 17:56:53.436106 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Sat Feb 02 17:56:53.436110 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     rv = self.handle_user_exception(e)
[Sat Feb 02 17:56:53.436113 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
[Sat Feb 02 17:56:53.436117 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     reraise(exc_type, exc_value, tb)
[Sat Feb 02 17:56:53.436120 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
[Sat Feb 02 17:56:53.436123 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     raise value
[Sat Feb 02 17:56:53.436127 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Sat Feb 02 17:56:53.436130 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     rv = self.dispatch_request()
[Sat Feb 02 17:56:53.436134 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
[Sat Feb 02 17:56:53.436145 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     return self.view_functions[rule.endpoint](**req.view_args)
[Sat Feb 02 17:56:53.436149 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/flask/moi/routes.py", line 57, in logged
[Sat Feb 02 17:56:53.436152 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     return render_template('logged.html', title = 'Welcome', form=form)
[Sat Feb 02 17:56:53.436155 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
[Sat Feb 02 17:56:53.436158 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
[Sat Feb 02 17:56:53.436161 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
[Sat Feb 02 17:56:53.436165 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     return self.get_template(template_name_or_list, parent, globals)
[Sat Feb 02 17:56:53.436168 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
[Sat Feb 02 17:56:53.436171 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     return self._load_template(name, self.make_globals(globals))
[Sat Feb 02 17:56:53.436174 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
[Sat Feb 02 17:56:53.436177 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     template = self.loader.load(self, name, globals)
[Sat Feb 02 17:56:53.436180 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
[Sat Feb 02 17:56:53.436183 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     code = environment.compile(source, name, filename)
[Sat Feb 02 17:56:53.436186 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
[Sat Feb 02 17:56:53.436189 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     self.handle_exception(exc_info, source_hint=source_hint)
[Sat Feb 02 17:56:53.436192 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
[Sat Feb 02 17:56:53.436195 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     reraise(exc_type, exc_value, tb)
[Sat Feb 02 17:56:53.436198 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
[Sat Feb 02 17:56:53.436201 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     raise value.with_traceback(tb)
[Sat Feb 02 17:56:53.436204 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/flask/moi/templates/logged.html", line 7, in template
[Sat Feb 02 17:56:53.436207 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     <div>
[Sat Feb 02 17:56:53.436209 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
[Sat Feb 02 17:56:53.436213 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     return Parser(self, source, name, encode_filename(filename)).parse()
[Sat Feb 02 17:56:53.436218 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
[Sat Feb 02 17:56:53.436222 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     result = nodes.Template(self.subparse(), lineno=1)
[Sat Feb 02 17:56:53.436225 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
[Sat Feb 02 17:56:53.436228 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     rv = self.parse_statement()
[Sat Feb 02 17:56:53.436231 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
[Sat Feb 02 17:56:53.436234 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     return getattr(self, 'parse_' + self.stream.current.value)()
[Sat Feb 02 17:56:53.436237 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
[Sat Feb 02 17:56:53.436240 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     node.body = self.parse_statements(('name:endblock',), drop_needle=True)
[Sat Feb 02 17:56:53.436243 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
[Sat Feb 02 17:56:53.436246 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     result = self.subparse(end_tokens)
[Sat Feb 02 17:56:53.436249 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 875, in subparse
[Sat Feb 02 17:56:53.436252 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     add_data(self.parse_tuple(with_condexpr=True))
[Sat Feb 02 17:56:53.436255 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 620, in parse_tuple
[Sat Feb 02 17:56:53.436258 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     args.append(parse())
[Sat Feb 02 17:56:53.436261 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 432, in parse_expression
[Sat Feb 02 17:56:53.436264 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     return self.parse_condexpr()
[Sat Feb 02 17:56:53.436267 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 437, in parse_condexpr
[Sat Feb 02 17:56:53.436270 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     expr1 = self.parse_or()
[Sat Feb 02 17:56:53.436273 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 450, in parse_or
[Sat Feb 02 17:56:53.436276 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     left = self.parse_and()
[Sat Feb 02 17:56:53.436279 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 459, in parse_and
[Sat Feb 02 17:56:53.436282 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     left = self.parse_not()
[Sat Feb 02 17:56:53.436285 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 470, in parse_not
[Sat Feb 02 17:56:53.436290 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     return self.parse_compare()
[Sat Feb 02 17:56:53.436293 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 480, in parse_compare
[Sat Feb 02 17:56:53.436297 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     ops.append(nodes.Operand(token_type, self.parse_math1()))
[Sat Feb 02 17:56:53.436300 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 496, in parse_math1
[Sat Feb 02 17:56:53.436303 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     left = self.parse_concat()
[Sat Feb 02 17:56:53.436306 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 507, in parse_concat
[Sat Feb 02 17:56:53.436309 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     args = [self.parse_math2()]
[Sat Feb 02 17:56:53.436311 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 517, in parse_math2
[Sat Feb 02 17:56:53.436314 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     left = self.parse_pow()
[Sat Feb 02 17:56:53.436317 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 528, in parse_pow
[Sat Feb 02 17:56:53.436320 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     left = self.parse_unary()
[Sat Feb 02 17:56:53.436323 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 546, in parse_unary
[Sat Feb 02 17:56:53.436326 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     node = self.parse_primary()
[Sat Feb 02 17:56:53.436329 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 583, in parse_primary
[Sat Feb 02 17:56:53.436332 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     self.fail("unexpected '%s'" % describe_token(token), token.lineno)
[Sat Feb 02 17:56:53.436335 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
[Sat Feb 02 17:56:53.436338 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386]     raise exc(msg, lineno, self.name, self.filename)
[Sat Feb 02 17:56:53.436343 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386] jinja2.exceptions.TemplateSyntaxError: unexpected '<'
[Sat Feb 02 17:56:53.436367 2019] [wsgi:error] [pid 8477:tid 139842836809472] [remote 127.0.0.1:46386] 
[Sat Feb 02 18:08:18.099482 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430] [2019-02-02 18:08:18,095] ERROR in app: Exception on /logged [GET]
[Sat Feb 02 18:08:18.099512 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430] Traceback (most recent call last):
[Sat Feb 02 18:08:18.099517 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
[Sat Feb 02 18:08:18.099520 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     response = self.full_dispatch_request()
[Sat Feb 02 18:08:18.099524 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Sat Feb 02 18:08:18.099534 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     rv = self.handle_user_exception(e)
[Sat Feb 02 18:08:18.099537 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
[Sat Feb 02 18:08:18.099540 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     reraise(exc_type, exc_value, tb)
[Sat Feb 02 18:08:18.099543 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
[Sat Feb 02 18:08:18.099546 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     raise value
[Sat Feb 02 18:08:18.099549 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Sat Feb 02 18:08:18.099552 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     rv = self.dispatch_request()
[Sat Feb 02 18:08:18.099555 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
[Sat Feb 02 18:08:18.099558 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     return self.view_functions[rule.endpoint](**req.view_args)
[Sat Feb 02 18:08:18.099561 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/flask/moi/routes.py", line 57, in logged
[Sat Feb 02 18:08:18.099564 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     return render_template('logged.html', title = 'Welcome', form=form)
[Sat Feb 02 18:08:18.099567 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
[Sat Feb 02 18:08:18.099570 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     context, ctx.app)
[Sat Feb 02 18:08:18.099586 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
[Sat Feb 02 18:08:18.099589 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     rv = template.render(context)
[Sat Feb 02 18:08:18.099593 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
[Sat Feb 02 18:08:18.099596 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     return original_render(self, *args, **kwargs)
[Sat Feb 02 18:08:18.099599 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
[Sat Feb 02 18:08:18.099602 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     return self.environment.handle_exception(exc_info, True)
[Sat Feb 02 18:08:18.099605 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
[Sat Feb 02 18:08:18.099609 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     reraise(exc_type, exc_value, tb)
[Sat Feb 02 18:08:18.099612 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
[Sat Feb 02 18:08:18.099615 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     raise value.with_traceback(tb)
[Sat Feb 02 18:08:18.099618 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/flask/moi/templates/logged.html", line 1, in top-level template code
[Sat Feb 02 18:08:18.099624 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     {% extends "layout.html" %}
[Sat Feb 02 18:08:18.099628 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/flask/moi/templates/layout.html", line 11, in top-level template code
[Sat Feb 02 18:08:18.099631 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     {% block content %}{% endblock %}
[Sat Feb 02 18:08:18.099634 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/flask/moi/templates/logged.html", line 20, in block "content"
[Sat Feb 02 18:08:18.099638 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     <a  href="{{ url_for('Logout') }}">Logout</a>
[Sat Feb 02 18:08:18.099641 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
[Sat Feb 02 18:08:18.099644 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     return appctx.app.handle_url_build_error(error, endpoint, values)
[Sat Feb 02 18:08:18.099648 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
[Sat Feb 02 18:08:18.099651 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     reraise(exc_type, exc_value, tb)
[Sat Feb 02 18:08:18.099654 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
[Sat Feb 02 18:08:18.099657 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     raise value
[Sat Feb 02 18:08:18.099660 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
[Sat Feb 02 18:08:18.099663 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     force_external=external)
[Sat Feb 02 18:08:18.099666 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]   File "/home/bartek/venvs/flask/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
[Sat Feb 02 18:08:18.099669 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430]     raise BuildError(endpoint, values, method, self)
[Sat Feb 02 18:08:18.099674 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430] werkzeug.routing.BuildError: Could not build url for endpoint 'Logout'. Did you mean 'logout' instead?
[Sat Feb 02 18:08:18.099701 2019] [wsgi:error] [pid 8747:tid 139842845202176] [remote 127.0.0.1:46430] 
